const fs = require('fs');
const path = require('path');

// Array of trending product types for realistic titles
const trendingProducts = [
    "Wireless Earbuds (New Model)", "Gaming Headset (50% Off)", "Smartwatch (Fitness Tracker)",
    "Bluetooth Speaker (Portable)", "Fast Car Charger (Type-C)", "Laptop Cooling Pad",
    "Office Chair (Ergonomic)", "Vitamin C Serum (Skincare)", "Running Shoes (Men's)",
    "Layered Necklace Set", "Backpack (Waterproof)", "Air Fryer (5L Capacity)"
];

// --- START: 99 DEALS GENERATE KARNE WALA LOGIC ---
const NUM_DEALS = 99; 
const realDealsData = [];

for (let i = 1; i <= NUM_DEALS; i++) {
    const price = Math.floor(Math.random() * 8000) + 500;
    const mrp = price + Math.floor(Math.random() * 3000) + 500;
    const randomProduct = trendingProducts[Math.floor(Math.random() * trendingProducts.length)];

    realDealsData.push({
        // 🟢 FIX 1: ASLI PRODUCT CATEGORY KA NAAM USE KARNA
        title: `${randomProduct} - Save Today! (ID: ${Math.random().toFixed(4)})`,
        price: price,
        mrp: mrp,
        savings: `Flat ${Math.round(((mrp - price) / mrp) * 100)}% Off`,
        // Affiliate Link ko aur specific banaya
        affiliate_link: `https://www.amazon.in/s?k=${randomProduct.replace(/\s/g, '+')}&tag=ascreation00f-21`, 
        // 🟢 FIX 2: WORKING PLACEHOLDER IMAGE
        image: "https://via.placeholder.com/150x150?text=AFFIMANIA+DEAL" 
    });
}
// --- END: 99 DEALS GENERATE KARNE WALA LOGIC ---


// Step 1: Deals Array ko JavaScript Code mein Convert karna
const dealsArrayString = JSON.stringify(realDealsData, null, 4);
const newDealsCode = `const dummyDeals = ${dealsArrayString};`;


// Step 2: index.html file ko padhna aur rewrite karna (rest of the logic)
const indexPath = path.join(__dirname, 'index.html');
let indexContent = fs.readFileSync(indexPath, 'utf8');
const startMarker = '// --- START: AUTOGENERATED DEALS DATA ---';
const endMarker = '// --- END: AUTOGENERATED DEALS DATA ---';

if (indexContent.includes(startMarker) && indexContent.includes(endMarker)) {
    const regex = new RegExp(`(${startMarker})[\\s\\S]*?(${endMarker})`, 'm'); 
    indexContent = indexContent.replace(regex, `${startMarker}\n${newDealsCode}\n${endMarker}`);
} else {
    console.error('CRITICAL ERROR: START/END markers not found. Cannot inject deals.');
    process.exit(1); 
}

fs.writeFileSync(indexPath, indexContent, 'utf8');
console.log('index.html updated successfully with new 99 deals data!');
