const fs = require('fs');
const path = require('path');

// --- START: 99 DEALS GENERATE KARNE WALA LOGIC ---
const NUM_DEALS = 99; 
const realDealsData = [];

for (let i = 1; i <= NUM_DEALS; i++) {
    const price = Math.floor(Math.random() * 8000) + 500;
    const mrp = price + Math.floor(Math.random() * 3000) + 500;

    realDealsData.push({
        // Title mein Unique ID, time aur date, taaki commit skip na ho
        title: `Trending Deal (Ref. #${i}) - ${new Date().toLocaleTimeString()} ${new Date().toLocaleDateString()}`,
        price: price,
        mrp: mrp,
        savings: `Flat ${Math.round(((mrp - price) / mrp) * 100)}% Off`,
        affiliate_link: `https://www.amazon.in/s?k=Top+Daily+Deal+${i}&tag=ascreation00f-21`,
        image: "https://example.com/placeholder.jpg" // Placeholder image URL
    });
}
// --- END: 99 DEALS GENERATE KARNE WALA LOGIC ---


// Step 1: Deals Array ko JavaScript Code mein Convert karna
const dealsArrayString = JSON.stringify(realDealsData, null, 4);
const newDealsCode = `const dummyDeals = ${dealsArrayString};`;

// Step 2: index.html file ko padhna
const indexPath = path.join(__dirname, 'index.html');
let indexContent = fs.readFileSync(indexPath, 'utf8');

// Step 3: Injection Markers aur Content Replace karna
const startMarker = '// --- START: AUTOGENERATED DEALS DATA ---';
const endMarker = '// --- END: AUTOGENERATED DEALS DATA ---';

if (indexContent.includes(startMarker) && indexContent.includes(endMarker)) {
    // Regex se markers ke beech ka content dhoondh kar replace karna
    const regex = new RegExp(`(?<=${startMarker}\\n)[\\s\\S]*?(?=\\n${endMarker})`, 'm');
    indexContent = indexContent.replace(regex, newDealsCode);
} else {
    // Agar markers nahi mile toh error dikhana
    console.error('CRITICAL ERROR: START/END markers not found. Cannot inject deals.');
    process.exit(1); // Script ko force fail karein
}

// Step 4: Updated index.html ko save karna
fs.writeFileSync(indexPath, indexContent, 'utf8');
console.log('index.html updated successfully with new 99 deals data!');
