const fs = require('fs');
const path = require('path');

// 🔐 Direct Keys (Security risk hai par undefined error theek ho jayega)
const ACCESS_KEY = 'AKPALTMLPD1766576649'; 
const SECRET_KEY = 'jC7vaQ1o9PGlVMcTC8Uu/RCUeSWuA8w60Sn2rX7z';
const PARTNER_TAG = 'ascreation00f-21';

const imagePool = {
    "Christmas Gift Hampers": [
        "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=500&q=80",
        "https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?w=500&q=80"
    ],
    "Party Speakers RGB": [
        "https://images.unsplash.com/photo-1589003077984-894e133dabab?w=500&q=80"
    ],
    "2026 Premium Planners": [
        "https://images.unsplash.com/photo-1506784919141-939e9e033d40?w=500&q=80"
    ]
};

const seasonalDatabase = {
    festive: {
        badge: "HOLIDAY SPECIAL 🎄🎆",
        title: "Celebrate <span class='text-yellow-400'>2026</span>",
        desc: "Automated hourly deals on Christmas Gifts and New Year Party supplies.",
        bg: "https://images.unsplash.com/photo-1467810563316-b5476525c0f9?q=80&w=1200",
        accent: "#B30000",
        categories: [
            {n: "Gifts", i: "🎁", l: "christmas+gift"},
            {n: "Party", i: "🔊", l: "party+speaker"},
            {n: "2026", i: "📅", l: "2026+planner"},
            {n: "Winter", i: "🧥", l: "winter+jacket"}
        ]
    }
};

const trendingProducts = Object.keys(imagePool);
const realDealsData = [];

for (let i = 1; i <= 52; i++) {
    const price = Math.floor(Math.random() * 8000) + 499;
    const mrp = price + Math.floor(Math.random() * 3000) + 500;
    const randomProduct = trendingProducts[Math.floor(Math.random() * trendingProducts.length)];
    
    realDealsData.push({
        title: `${randomProduct} - Best Seller #${i}`,
        price: price,
        mrp: mrp,
        savings: `Flat ${Math.round(((mrp - price) / mrp) * 100)}% Off`,
        affiliate_link: `https://www.amazon.in/s?k=${randomProduct.replace(/\s/g, '+')}&tag=${PARTNER_TAG}`,
        image: imagePool[randomProduct][0]
    });
}

const indexPath = path.join(__dirname, 'index.html');
let content = fs.readFileSync(indexPath, 'utf8');

// Variable names exact match hone chahiye
content = content.replace(/(\/\/ --- START: AUTOGENERATED DEALS DATA ---)[\s\S]*?(\/\/ --- END: AUTOGENERATED DEALS DATA ---)/, 
    `$1\nconst dummyDeals = ${JSON.stringify(realDealsData, null, 4)};\n$2`);

content = content.replace(/(\/\/ --- START: CONTEXT DATA ---)[\s\S]*?(\/\/ --- END: CONTEXT DATA ---)/, 
    `$1\nconst affimaniaContext = ${JSON.stringify(seasonalDatabase.festive)};\n$2`);

fs.writeFileSync(indexPath, content);
console.log('✅ Success: Data Written to index.html');
